// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RealOrchestratorClient is the client API for RealOrchestrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RealOrchestratorClient interface {
	GetUserByName(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*User, error)
	GetUser(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*User, error)
}

type realOrchestratorClient struct {
	cc grpc.ClientConnInterface
}

func NewRealOrchestratorClient(cc grpc.ClientConnInterface) RealOrchestratorClient {
	return &realOrchestratorClient{cc}
}

func (c *realOrchestratorClient) GetUserByName(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/real_orchestrator_proto.real_orchestrator/GetUserByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *realOrchestratorClient) GetUser(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/real_orchestrator_proto.real_orchestrator/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RealOrchestratorServer is the server API for RealOrchestrator service.
// All implementations must embed UnimplementedRealOrchestratorServer
// for forward compatibility
type RealOrchestratorServer interface {
	GetUserByName(context.Context, *NameRequest) (*User, error)
	GetUser(context.Context, *NameRequest) (*User, error)
	mustEmbedUnimplementedRealOrchestratorServer()
}

// UnimplementedRealOrchestratorServer must be embedded to have forward compatible implementations.
type UnimplementedRealOrchestratorServer struct {
}

func (UnimplementedRealOrchestratorServer) GetUserByName(context.Context, *NameRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByName not implemented")
}
func (UnimplementedRealOrchestratorServer) GetUser(context.Context, *NameRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedRealOrchestratorServer) mustEmbedUnimplementedRealOrchestratorServer() {}

// UnsafeRealOrchestratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealOrchestratorServer will
// result in compilation errors.
type UnsafeRealOrchestratorServer interface {
	mustEmbedUnimplementedRealOrchestratorServer()
}

func RegisterRealOrchestratorServer(s grpc.ServiceRegistrar, srv RealOrchestratorServer) {
	s.RegisterService(&RealOrchestrator_ServiceDesc, srv)
}

func _RealOrchestrator_GetUserByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealOrchestratorServer).GetUserByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/real_orchestrator_proto.real_orchestrator/GetUserByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealOrchestratorServer).GetUserByName(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RealOrchestrator_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RealOrchestratorServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/real_orchestrator_proto.real_orchestrator/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RealOrchestratorServer).GetUser(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RealOrchestrator_ServiceDesc is the grpc.ServiceDesc for RealOrchestrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealOrchestrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "real_orchestrator_proto.real_orchestrator",
	HandlerType: (*RealOrchestratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByName",
			Handler:    _RealOrchestrator_GetUserByName_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _RealOrchestrator_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logic/proto/real_orchestrator.proto",
}
