// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DatamockClient is the client API for Datamock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DatamockClient interface {
	GetMockUserData(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*User, error)
}

type datamockClient struct {
	cc grpc.ClientConnInterface
}

func NewDatamockClient(cc grpc.ClientConnInterface) DatamockClient {
	return &datamockClient{cc}
}

func (c *datamockClient) GetMockUserData(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.datamock/GetMockUserData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DatamockServer is the server API for Datamock service.
// All implementations must embed UnimplementedDatamockServer
// for forward compatibility
type DatamockServer interface {
	GetMockUserData(context.Context, *NameRequest) (*User, error)
	mustEmbedUnimplementedDatamockServer()
}

// UnimplementedDatamockServer must be embedded to have forward compatible implementations.
type UnimplementedDatamockServer struct {
}

func (UnimplementedDatamockServer) GetMockUserData(context.Context, *NameRequest) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMockUserData not implemented")
}
func (UnimplementedDatamockServer) mustEmbedUnimplementedDatamockServer() {}

// UnsafeDatamockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DatamockServer will
// result in compilation errors.
type UnsafeDatamockServer interface {
	mustEmbedUnimplementedDatamockServer()
}

func RegisterDatamockServer(s grpc.ServiceRegistrar, srv DatamockServer) {
	s.RegisterService(&Datamock_ServiceDesc, srv)
}

func _Datamock_GetMockUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatamockServer).GetMockUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.datamock/GetMockUserData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatamockServer).GetMockUserData(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Datamock_ServiceDesc is the grpc.ServiceDesc for Datamock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Datamock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.datamock",
	HandlerType: (*DatamockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMockUserData",
			Handler:    _Datamock_GetMockUserData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/datamock.proto",
}
